apiVersion: v1
kind: ConfigMap
metadata:
  name: s3desk-caddy
  namespace: s3desk
data:
  Caddyfile: |
    {
      auto_https off
    }

    :8443 {
      tls /etc/caddy/tls/tls.crt /etc/caddy/tls/tls.key
      reverse_proxy 127.0.0.1:8080
    }
