ingress:
  enabled: false

istio:
  virtualService:
    enabled: true
    gateways:
      - istio-system/s3desk-gw
    hosts:
      - s3desk.k8s.homelabird.com

server:
  allowedHosts:
    - s3desk.k8s.homelabird.com

rclone:
  retryJitterRatio: 0.2

extraEnv:
  - name: RCLONE_DOWNLOAD_MULTI_THREAD_STREAMS
    value: "8"
  - name: RCLONE_DOWNLOAD_MULTI_THREAD_CUTOFF_MIB
    value: "64"
  - name: RCLONE_DOWNLOAD_BUFFER_SIZE_MIB
    value: "32"
