{{- $hasValues := or (ne (trim .Values.server.apiToken) "") (ne (trim .Values.server.encryptionKey) "") (ne (trim .Values.db.databaseUrl) "") -}}
{{- if and (not .Values.secrets.existingSecret) $hasValues -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3desk.fullname" . }}
  labels:
    {{- include "s3desk.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if ne (trim .Values.server.apiToken) "" }}
  {{ .Values.secrets.apiTokenKey }}: {{ .Values.server.apiToken | quote }}
  {{- end }}
  {{- if ne (trim .Values.server.encryptionKey) "" }}
  {{ .Values.secrets.encryptionKeyKey }}: {{ .Values.server.encryptionKey | quote }}
  {{- end }}
  {{- if ne (trim .Values.db.databaseUrl) "" }}
  {{ .Values.secrets.databaseUrlKey }}: {{ .Values.db.databaseUrl | quote }}
  {{- end }}
{{- end }}
